// <auto-generated />
namespace CarFuel.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class car_addOwner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(car_addOwner));
        
        string IMigrationMetadata.Id
        {
            get { return "201611110454366_car_addOwner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
