// <auto-generated />
namespace CarFuel.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addmorecarinfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmorecarinfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201611110256264_add more car info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
